# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\BugBot\ui\choose_user.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_choose_user(object):
    def setupUi(self, choose_user):
        choose_user.setObjectName("choose_user")
        choose_user.resize(215, 276)
        self.verticalLayout = QtWidgets.QVBoxLayout(choose_user)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listWidget = QtWidgets.QListWidget(choose_user)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.lineEdit = QtWidgets.QLineEdit(choose_user)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.buttonBox = QtWidgets.QDialogButtonBox(choose_user)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(choose_user)
        self.buttonBox.accepted.connect(choose_user.accept)
        self.buttonBox.rejected.connect(choose_user.reject)
        QtCore.QMetaObject.connectSlotsByName(choose_user)

    def retranslateUi(self, choose_user):
        self.listWidget.itemClicked()
        self.listWidget.addItems()
        _translate = QtCore.QCoreApplication.translate
        choose_user.setWindowTitle(_translate("choose_user", "Dialog"))
